import type { Metadata } from 'next'
import Link from 'next/link'
import { auth } from '@/auth'
import ProductForm from '@/components/admin/ProductForm'
import { createProduct } from '@/lib/products'
import { createMediaRow, syncProductImageCache } from '@/lib/media'
import { parseProductForm } from '@/lib/validation/productSchema'
import type { ProductFormData } from '@/types'
import { revalidatePath } from 'next/cache'

export const metadata: Metadata = { title: 'Nuevo producto — Admin' }

async function handleCreate(data: ProductFormData): Promise<{ success: boolean; error?: string }> {
  'use server'

  // 1) Auth gate — refuse early with a clear message if the session is gone.
  const session = await auth()
  if (!session) {
    console.error('[CREATE] No session — refusing insert')
    return { success: false, error: 'Sesión expirada. Vuelve a iniciar sesión.' }
  }

  console.log('[CREATE] step=start', {
    name: data.name,
    shortName: data.shortName,
    category: data.category,
    price: data.price,
    stock: data.stock,
    featuresCount: data.features?.length ?? 0,
    hasImage: Boolean(data.imageUrl),
  })

  // 2) Server-side validation (Zod with coerce.number + enum).
  const parsed = parseProductForm(data)
  if (!parsed.ok) {
    console.warn('[CREATE] step=validate failed:', parsed)
    return {
      success: false,
      error: parsed.field
        ? `${parsed.field}: ${parsed.error}`
        : parsed.error,
    }
  }
  const v = parsed.data

  // imageFile is always undefined here — upload happens client-side via /api/admin/upload
  const imageUrl = data.imageUrl ?? '/img.jpg'

  console.log('[CREATE] step=insert', { imageUrl, priceCoerced: v.price, stockCoerced: v.stock })

  // 3) Insert via service role. createProduct now returns a discriminated
  //    result so we can bubble Supabase's actual message + hint up to the UI.
  const result = await createProduct({
    name: v.name,
    short_name: v.shortName,
    category: v.category,
    price: v.price,
    description: v.description || null,
    long_description: v.longDescription || null,
    specs: v.specs && Object.keys(v.specs).length > 0 ? v.specs : null,
    slug: null, // auto-generated by the products.auto_generate_slug() trigger
    image_url: imageUrl,
    badge: v.badge || null,
    stock: v.stock,
    features: v.features,
  })

  if (!result.ok) {
    console.error('[CREATE] step=insert FAILED:', result)
    return {
      success: false,
      error: result.hint ? `${result.error} — ${result.hint}` : result.error,
    }
  }

  const realProductId = result.product.id
  console.log('[CREATE] step=success', { id: realProductId, slug: result.product.slug })

  // 4) Commit any draft media uploaded before the product existed.
  //    In the "new" flow, MediaList runs in draft mode: files are uploaded to
  //    Storage right away (so we already have public URLs), but no
  //    product_media rows are inserted until the product itself exists.
  //    Now that we have a real product id, insert those rows here.
  //    Files live under a folder named after the pre-generated UUID used
  //    during the draft; the public URLs still work fine, so we don't need
  //    to move them.
  const draftMedia = data.media ?? []
  if (draftMedia.length > 0) {
    console.log('[CREATE] step=commit_media', { count: draftMedia.length, realProductId })
    let committed = 0
    let failed = 0
    for (let i = 0; i < draftMedia.length; i++) {
      const m = draftMedia[i]
      const row = await createMediaRow({
        productId: realProductId,
        url: m.url,
        mediaType: m.mediaType,
        position: i, // reindex so positions are strictly 0..n-1
        isPrimary: m.isPrimary,
      })
      if (row) committed++
      else failed++
    }
    console.log('[CREATE] step=commit_media done', { committed, failed })

    // Make sure products.image_url mirrors whichever image ended up primary
    // (or the first image, if no explicit primary). Without this the home
    // and catalog cards would keep showing the placeholder.
    await syncProductImageCache(realProductId)
  }

  revalidatePath('/')
  revalidatePath('/admin/products')
  revalidatePath(`/producto/${result.product.slug}`)
  return { success: true }
}

export default function NewProductPage() {
  return (
    <div className="p-6 lg:p-8">
      <nav className="mb-6 flex items-center gap-2 text-sm text-muted" aria-label="Breadcrumb">
        <Link href="/admin/products" className="hover:text-white transition-colors">Productos</Link>
        <span aria-hidden="true">/</span>
        <span className="text-white">Nuevo</span>
      </nav>
      <h1 className="mb-8 text-2xl font-bold text-white">Crear producto</h1>
      <ProductForm onSubmit={handleCreate} />
    </div>
  )
}
