import type { Metadata } from 'next'
import Link from 'next/link'
import { auth } from '@/auth'
import ProductForm from '@/components/admin/ProductForm'
import { createProduct } from '@/lib/products'
import { parseProductForm } from '@/lib/validation/productSchema'
import type { ProductFormData } from '@/types'
import { revalidatePath } from 'next/cache'

export const metadata: Metadata = { title: 'Nuevo producto — Admin' }

async function handleCreate(data: ProductFormData): Promise<{ success: boolean; error?: string }> {
  'use server'

  // 1) Auth gate — refuse early with a clear message if the session is gone.
  const session = await auth()
  if (!session) {
    console.error('[CREATE] No session — refusing insert')
    return { success: false, error: 'Sesión expirada. Vuelve a iniciar sesión.' }
  }

  console.log('[CREATE] step=start', {
    name: data.name,
    shortName: data.shortName,
    category: data.category,
    price: data.price,
    stock: data.stock,
    featuresCount: data.features?.length ?? 0,
    hasImage: Boolean(data.imageUrl),
  })

  // 2) Server-side validation (Zod with coerce.number + enum).
  const parsed = parseProductForm(data)
  if (!parsed.ok) {
    console.warn('[CREATE] step=validate failed:', parsed)
    return {
      success: false,
      error: parsed.field
        ? `${parsed.field}: ${parsed.error}`
        : parsed.error,
    }
  }
  const v = parsed.data

  // imageFile is always undefined here — upload happens client-side via /api/admin/upload
  const imageUrl = data.imageUrl ?? '/img.jpg'

  console.log('[CREATE] step=insert', { imageUrl, priceCoerced: v.price, stockCoerced: v.stock })

  // 3) Insert via service role. createProduct now returns a discriminated
  //    result so we can bubble Supabase's actual message + hint up to the UI.
  const result = await createProduct({
    name: v.name,
    short_name: v.shortName,
    category: v.category,
    price: v.price,
    description: v.description || null,
    long_description: v.longDescription || null,
    specs: v.specs && Object.keys(v.specs).length > 0 ? v.specs : null,
    slug: null, // auto-generated by the products.auto_generate_slug() trigger
    image_url: imageUrl,
    badge: v.badge || null,
    stock: v.stock,
    features: v.features,
  })

  if (!result.ok) {
    console.error('[CREATE] step=insert FAILED:', result)
    return {
      success: false,
      error: result.hint ? `${result.error} — ${result.hint}` : result.error,
    }
  }

  console.log('[CREATE] step=success', { id: result.product.id, slug: result.product.slug })

  revalidatePath('/')
  revalidatePath('/admin/products')
  return { success: true }
}

export default function NewProductPage() {
  return (
    <div className="p-6 lg:p-8">
      <nav className="mb-6 flex items-center gap-2 text-sm text-muted" aria-label="Breadcrumb">
        <Link href="/admin/products" className="hover:text-white transition-colors">Productos</Link>
        <span aria-hidden="true">/</span>
        <span className="text-white">Nuevo</span>
      </nav>
      <h1 className="mb-8 text-2xl font-bold text-white">Crear producto</h1>
      <ProductForm onSubmit={handleCreate} />
    </div>
  )
}
